import { useState } from 'react';
import { CalendarPlus, CheckCircle2 } from 'lucide-react';
import { Badge, Card, Field, inputClass } from '../components/Forms';
import { useAppData } from '../hooks/useAppData';

export default function Tasks() {
  const { subjects, tasks, addTask, updateTask } = useAppData();
  const [form, setForm] = useState({ titulo: '', descricao: '', subjectId: subjects[0]?.id || '', dataEntrega: '2026-05-15', tipo: 'tarefa', prioridade: 'média', status: 'pendente' });
  const submit = (event) => { event.preventDefault(); addTask(form); setForm({ ...form, titulo: '', descricao: '' }); };
  return <div className="mx-auto grid max-w-7xl gap-6 xl:grid-cols-[420px_1fr]"><Card><h1 className="mb-5 flex items-center gap-2 text-2xl font-black"><CalendarPlus/> Nova atividade</h1><form onSubmit={submit} className="grid gap-4"><Field label="Título"><input required className={inputClass} value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })}/></Field><Field label="Descrição"><textarea className={inputClass} value={form.descricao} onChange={(e) => setForm({ ...form, descricao: e.target.value })}/></Field><Field label="Matéria"><select className={inputClass} value={form.subjectId} onChange={(e) => setForm({ ...form, subjectId: e.target.value })}>{subjects.map((s) => <option key={s.id} value={s.id}>{s.nome}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Entrega"><input type="date" className={inputClass} value={form.dataEntrega} onChange={(e) => setForm({ ...form, dataEntrega: e.target.value })}/></Field><Field label="Tipo"><select className={inputClass} value={form.tipo} onChange={(e) => setForm({ ...form, tipo: e.target.value })}>{['tarefa','prova','trabalho','revisão','apresentação','evento'].map((x) => <option key={x}>{x}</option>)}</select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Prioridade"><select className={inputClass} value={form.prioridade} onChange={(e) => setForm({ ...form, prioridade: e.target.value })}>{['baixa','média','alta'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Status"><select className={inputClass} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{['pendente','em andamento','concluído'].map((x) => <option key={x}>{x}</option>)}</select></Field></div><button className="rounded-2xl bg-teal-400 py-3 font-black text-slate-950">Salvar tarefa</button></form></Card>
  <section className="space-y-4"><h1 className="text-3xl font-black">Tarefas e atividades</h1>{tasks.map((task) => <Card key={task.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap gap-2"><Badge tone={task.tipo === 'prova' ? 'red' : 'teal'}>{task.tipo}</Badge><Badge>{task.prioridade}</Badge></div><h2 className="mt-3 text-xl font-black">{task.titulo}</h2><p className="text-sm text-slate-400">{task.descricao}</p></div><div className="text-right"><p className="font-bold">{task.dataEntrega}</p><button onClick={() => updateTask(task.id, { status: 'concluído' })} className="mt-3 inline-flex items-center gap-2 rounded-2xl border border-white/10 px-4 py-2 text-sm"><CheckCircle2 size={16}/> Concluir</button></div></div></Card>)}</section></div>;
}
